post_hooks:
  - "rm ../../../src/galileo/resources/README.md"
  # Commenting this out for now as it's not working
  # - 'python ../../../scripts/patch_http_validation_error.py "../../../src/galileo/resources/models/http_validation_error.py"'
literal_enums: true
